text = "Enter some text: "
user_input = input(text)
output = user_input.replace("a", "4")
output= output.replace("b", "8")
output = output.replace("e", "3")
output = output.replace("i", "1")
output = output.replace("o", "0")
output = output.replace("s", "5")
output = output.replace("t", "7")
print(output)